/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGFreqDisplaySettings.h
 *
 * Frequency Display settings
 */

#ifndef SWGFreqDisplaySettings_H_
#define SWGFreqDisplaySettings_H_

#include <QJsonObject>


#include "SWGRollupState.h"
#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGFreqDisplaySettings: public SWGObject {
public:
    SWGFreqDisplaySettings();
    SWGFreqDisplaySettings(QString* json);
    virtual ~SWGFreqDisplaySettings();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGFreqDisplaySettings* fromJson(QString &jsonString) override;

    QString* getSelectedChannel();
    void setSelectedChannel(QString* selected_channel);

    QString* getFontName();
    void setFontName(QString* font_name);

    qint32 getTransparentBackground();
    void setTransparentBackground(qint32 transparent_background);

    qint32 getDisplayMode();
    void setDisplayMode(qint32 display_mode);

    qint32 getSpeechEnabled();
    void setSpeechEnabled(qint32 speech_enabled);

    qint32 getFrequencyUnits();
    void setFrequencyUnits(qint32 frequency_units);

    qint32 getShowUnits();
    void setShowUnits(qint32 show_units);

    qint32 getPowerDecimalPlaces();
    void setPowerDecimalPlaces(qint32 power_decimal_places);

    qint32 getTextcolor();
    void setTextcolor(qint32 textcolor);

    qint32 getDropShadowEnabled();
    void setDropShadowEnabled(qint32 drop_shadow_enabled);

    QString* getTitle();
    void setTitle(QString* title);

    qint32 getRgbColor();
    void setRgbColor(qint32 rgb_color);

    qint32 getUseReverseApi();
    void setUseReverseApi(qint32 use_reverse_api);

    QString* getReverseApiAddress();
    void setReverseApiAddress(QString* reverse_api_address);

    qint32 getReverseApiPort();
    void setReverseApiPort(qint32 reverse_api_port);

    qint32 getReverseApiFeatureSetIndex();
    void setReverseApiFeatureSetIndex(qint32 reverse_api_feature_set_index);

    qint32 getReverseApiFeatureIndex();
    void setReverseApiFeatureIndex(qint32 reverse_api_feature_index);

    SWGRollupState* getRollupState();
    void setRollupState(SWGRollupState* rollup_state);


    virtual bool isSet() override;

private:
    QString* selected_channel;
    bool m_selected_channel_isSet;

    QString* font_name;
    bool m_font_name_isSet;

    qint32 transparent_background;
    bool m_transparent_background_isSet;

    qint32 display_mode;
    bool m_display_mode_isSet;

    qint32 speech_enabled;
    bool m_speech_enabled_isSet;

    qint32 frequency_units;
    bool m_frequency_units_isSet;

    qint32 show_units;
    bool m_show_units_isSet;

    qint32 power_decimal_places;
    bool m_power_decimal_places_isSet;

    qint32 textcolor;
    bool m_textcolor_isSet;

    qint32 drop_shadow_enabled;
    bool m_drop_shadow_enabled_isSet;

    QString* title;
    bool m_title_isSet;

    qint32 rgb_color;
    bool m_rgb_color_isSet;

    qint32 use_reverse_api;
    bool m_use_reverse_api_isSet;

    QString* reverse_api_address;
    bool m_reverse_api_address_isSet;

    qint32 reverse_api_port;
    bool m_reverse_api_port_isSet;

    qint32 reverse_api_feature_set_index;
    bool m_reverse_api_feature_set_index_isSet;

    qint32 reverse_api_feature_index;
    bool m_reverse_api_feature_index_isSet;

    SWGRollupState* rollup_state;
    bool m_rollup_state_isSet;

};

}

#endif /* SWGFreqDisplaySettings_H_ */
